FROM tutum/ubuntu:trusty

RUN mkdir -p /home/.ssh
RUN chmod 0755 /home
RUN chmod 0700 /home/.ssh
ADD deploy.sh /home
RUN chmod +x /home/deploy.sh
RUN echo "    IdentityFile ~/.ssh/id_rsa" >> /etc/ssh/ssh_config
